CREATE ROLE gones_app LOGIN PASSWORD 'local-app-only';
GRANT CONNECT ON DATABASE gones TO gones_app;
GRANT USAGE ON SCHEMA public TO gones_app;
ALTER DEFAULT PRIVILEGES FOR ROLE gones_migration IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gones_app;
ALTER DEFAULT PRIVILEGES FOR ROLE gones_migration IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO gones_app;
