// <auto-generated />
using System;
using Gones.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gones.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GonesDbContext))]
    [Migration("20260801152724_AddAdminBootstrapAndFormats")]
    partial class AddAdminBootstrapAndFormats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gones.Domain.Catalog.TournamentFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tournament_formats");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tournament_formats_slug");

                    b.HasIndex("DeletedAt", "SortOrder", "Name")
                        .HasDatabaseName("ix_tournament_formats_deleted_at_sort_order_name");

                    b.ToTable("tournament_formats", null, t =>
                        {
                            t.HasCheckConstraint("ck_tournament_format_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.AccountActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("NormalizedTargetEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_target_email");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.Property<Instant?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("target_email");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_account_action_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_action_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ix_account_action_tokens_user_id_purpose")
                        .HasFilter("consumed_at IS NULL AND superseded_at IS NULL");

                    b.ToTable("account_action_tokens", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("provider_email");

                    b.Property<Instant>("ProviderEmailUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_email_updated_at");

                    b.Property<bool>("ProviderEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("provider_email_verified");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subject");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_provider_provider_subject");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_user_id_provider");

                    b.ToTable("external_identities", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.OAuthAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("completion_hash")
                        .IsFixedLength();

                    b.Property<Instant?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("CorrelationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("correlation_hash")
                        .IsFixedLength();

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailVerificationHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("email_verification_hash")
                        .IsFixedLength();

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProposedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("proposed_email");

                    b.Property<string>("ProposedFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposed_first_name");

                    b.Property<string>("ProposedLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proposed_last_name");

                    b.Property<string>("ProposedUsername")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("proposed_username");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("provider_email");

                    b.Property<bool>("ProviderEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("provider_email_verified");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subject");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("state_hash")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_oauth_attempts");

                    b.HasIndex("CompletionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_attempts_completion_hash");

                    b.HasIndex("EmailVerificationHash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_attempts_email_verification_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_oauth_attempts_expires_at");

                    b.HasIndex("StateHash")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_attempts_state_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_oauth_attempts_user_id");

                    b.ToTable("oauth_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_label");

                    b.Property<Instant>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<Instant>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("revocation_reason");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_sessions_user_id_revoked_at");

                    b.ToTable("refresh_sessions", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedById")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.UserEmailHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Instant>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Instant?>("RedactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redacted_at");

                    b.Property<Instant>("RetainUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retain_until");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_email_histories");

                    b.HasIndex("RedactedAt", "RetainUntil")
                        .HasDatabaseName("ix_user_email_histories_redacted_at_retain_until");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("ix_user_email_histories_user_id_recorded_at");

                    b.ToTable("user_email_histories", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBirthYearPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_birth_year_public");

                    b.Property<bool>("IsFirstNamePublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_first_name_public");

                    b.Property<bool>("IsLastNamePublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_last_name_public");

                    b.Property<bool>("IsLocationPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_location_public");

                    b.Property<bool>("IsPreferredLanguagePublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred_language_public");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_normalized_username");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles", t =>
                        {
                            t.HasCheckConstraint("ck_user_profile_birth_year", "birth_year IS NULL OR birth_year >= 1900");

                            t.HasCheckConstraint("ck_user_profile_language", "preferred_language IN ('fr', 'en')");

                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Notifications.NotificationOutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Instant>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("correlation_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedupe_key");

                    b.Property<Instant?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("Recipient")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient");

                    b.Property<Instant?>("ScrubbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scrubbed_at");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<string>("TemplateModelJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("template_model_json");

                    b.Property<Guid?>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_outbox_dedupe_key");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_notification_outbox_tournament_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_outbox_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_notification_outbox_status_created_at");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("ix_notification_outbox_status_lease_expires_at");

                    b.HasIndex("Status", "AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_notification_outbox_status_available_at_created_at");

                    b.ToTable("notification_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_outbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_notification_outbox_state", "(status = 'Pending' AND lease_token IS NULL AND lease_expires_at IS NULL AND sent_at IS NULL AND dead_lettered_at IS NULL AND scrubbed_at IS NULL AND recipient IS NOT NULL AND template_model_json IS NOT NULL)\nOR (status = 'Sending' AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL AND sent_at IS NULL AND dead_lettered_at IS NULL AND scrubbed_at IS NULL AND recipient IS NOT NULL AND template_model_json IS NOT NULL)\nOR (status = 'Sent' AND lease_token IS NULL AND lease_expires_at IS NULL AND sent_at IS NOT NULL AND dead_lettered_at IS NULL AND scrubbed_at IS NOT NULL AND recipient IS NULL AND template_model_json IS NULL)\nOR (status = 'DeadLetter' AND lease_token IS NULL AND lease_expires_at IS NULL AND sent_at IS NULL AND dead_lettered_at IS NOT NULL AND scrubbed_at IS NOT NULL AND recipient IS NULL AND template_model_json IS NULL)");

                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RedactedDiff")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("redacted_diff");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_audit_records");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_records_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_records_entity_type_entity_id");

                    b.ToTable("audit_records", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_scope_key");

                    b.ToTable("idempotency_records", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.OutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_records");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_records_processed_at_occurred_at");

                    b.ToTable("outbox_records", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.SchemaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_schema_versions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_schema_versions_name");

                    b.ToTable("schema_versions", t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.SystemMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<Guid?>("ConsumedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_by_user_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_system_markers");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_markers_key");

                    b.ToTable("system_markers", null, t =>
                        {
                            t.HasCheckConstraint("ck_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Gones.Domain.Persistence.WorkerHeartbeatRecord", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.Property<Instant>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("WorkerId")
                        .HasName("pk_worker_heartbeats");

                    b.ToTable("worker_heartbeats");
                });

            modelBuilder.Entity("Gones.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("GlobalRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("global_role");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("GlobalRole")
                        .HasDatabaseName("ix_asp_net_users_global_role");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_asp_net_users_global_role", "global_role IN ('User', 'Organizer', 'Admin')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Gones.Domain.Identity.AccountActionToken", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_action_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_asp_net_users_user_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.OAuthAttempt", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_oauth_attempts_asp_net_users_user_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_asp_net_users_user_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Gones.Domain.Identity.RefreshToken", null)
                        .WithOne()
                        .HasForeignKey("Gones.Domain.Identity.RefreshToken", "ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_id");

                    b.HasOne("Gones.Domain.Identity.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_refresh_sessions_session_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.UserEmailHistory", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_email_histories_asp_net_users_user_id");
                });

            modelBuilder.Entity("Gones.Domain.Identity.UserProfile", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Gones.Domain.Identity.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Gones.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
